### ISSUE TITLE
Trouble running npm install: packages out of date?

### ISSUE THREAD

**Issue by 2nickpick** [jpotts18/mean-stack-relational#22]
New to node/express and would love to test out the mysql mean stack, but am running into issues getting the project set up. 

I'm currently running node v0.12.1. 

Here's a small screenshot of the ending output:

![image](https://cloud.githubusercontent.com/assets/3085512/6884138/9873c240-d5ad-11e4-8d02-9fae22573552.png)

**Comment by 2nickpick** [comment]
Hm, it seems like some of these modules may have a dependency on python2, as opposed to python3, to be installed correctly. That's interesting.

**Comment by akocmark** [comment]
@2nickpick  hi there, have you already solved this issue? because i ran into this issue too. Thanks. 
My version of nodejs is v.0.12.2

**Comment by jpotts18** [comment]
I did not test my project on Windows. I am sorry but I bet that is one of the problems.

**Comment by akocmark** [comment]
i solved it by removing sqlite3 from package.json
@jpotts18 i migrated this project to express 4.x btw. it's running all good now. thank you so much!

**Comment by jpotts18** [comment]
Cool would you like to send me a PR and I can merge in your changes to help other people?
