### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by stherrienaspnet** [jpotts18/mean-stack-relational#23]
Hello, i started a new touchscreen web application from this wanderfull solution. On the signin server page i need to use the angular js directives  ng-keypad. The problem is that i cannot access anything from my client controller. There is something i do not completely anderstand. I can see in chrome that my controller files is really loaded when going into signin page but nothing is accessible into the scope.

Any help will be greatly apreciated since i'm stock.
You can reach me at stherrienaspnet@gmail.com

**Comment by jpotts18** [comment]
This seem like more of angular problem than an issue with my code.

**Comment by stherrienaspnet** [comment]
Hello Jeff,

Your code is working perfectly, i thing i just need some advice and i think
you are the best person for that since this your project and you have a
really good anderstandof it , better than me for sure :) Jeff how can i use
an angular.js controller for the signin page? Could i achieve this easily
with some minor change? I will not use the signup page.

Thanks you for your time,
