### ISSUE TITLE
older sequelize-mysql instead of latest sequelize is present currently

### ISSUE THREAD

**Issue by chaudhryjunaid** [jpotts18/mean-stack-relational#27]
Sequelize-mysql is being used which is an older unmaintained module. Sequelize-mysql defaults to sequelize 1.7.0 which misses support for many newer sequelize features and bug fixes.

**Comment by chaudhry-junaid** [comment]
This can be closed as changes for using the version 3.0 of sequelize have been merged into the master branch.

**Comment by chaudhryjunaid** [comment]
Closing as this has been fixed.

**Comment by jpotts18** [comment]
:+1:
