### ISSUE TITLE
New Express 4 code does not work in production mode 

### ISSUE THREAD

**Issue by chaudhryjunaid** [jpotts18/mean-stack-relational#29]
because development flag encapsulates many middleware and express configuration in config/express.js

I can fix it when I get some time.

**Comment by chaudhry-junaid** [comment]
fixed in latest pull request

**Comment by jpotts18** [comment]
I have moved away from writing a lot of javascript and I want to see this library get the attention that it deserves. Would you be interested in becoming a collaborator on this project?

**Comment by chaudhry-junaid** [comment]
Yes, absolutely. Thank you!

**Comment by chaudhry-junaid** [comment]
My primary expertise is in Express, Sequelize and Node.js and I can help with the corresponding parts of the project more than the Angular part. I have some previous experience with Angular anyway.

**Comment by jpotts18** [comment]
Can we set up a google hangout? I'd like to collaborate with you and create a project roadmap.

**Comment by chaudhry-junaid** [comment]
Yes sure. I'd prefer text chat to voice conversation, however.

**Comment by jpotts18** [comment]
Okay I will chat you through google hangouts

**Comment by chaudhryjunaid** [comment]
Closing as this is fixed. :)

**Comment by jpotts18** [comment]
:shipit:
