### ISSUE TITLE
How to use raw query with this repo?

### ISSUE THREAD

**Issue by ammarshadiq** [jpotts18/mean-stack-relational#30]
I tried various things to enable me to do raw query with this repo to no success. My ultimate goal is to be able to do complex query like for hierarchical data operation on a table. but i haven't been able to do a very simple raw query like "select * from article".
could any one help me?

**Comment by jpotts18** [comment]
You should read up on Sequelize that is the ORM that is used

http://docs.sequelizejs.com/en/latest/docs/raw-queries/

**Comment by ammarshadiq** [comment]
on "public/js/controller/articles.js" i've tried to put:

$scope.qry = function () {
        Articles.query("select * from Articles limit 1;", { model: Articles }).then(function(articles){
               $scope.articles = articles;
        });
};

and call the function from "public/views/article/list.html" using {{qry()}}

and when i call the page on a browser, the tab would be freezes and the console log littered with endless error.

could you give me some hint?

**Comment by jpotts18** [comment]
You are making the query from Angular.js which doesn't have access to the database. You will need to make the request from the Node.js side.

https://github.com/jpotts18/mean-stack-relational/blob/master/app/controllers/articles.js

```js
exports.all = function(req, res) {
    /// Custom query in the node.js backend
    db.Article.query("select * from articles limit 5").then(function(articles){
        return res.jsonp(articles);
    }).catch(function(err){
        return res.render('error', {
            error: err,
            status: 500
        });
    });
};
```
Then you will want to change the Angular.js side of the app in the services and controllers

https://github.com/jpotts18/mean-stack-relational/blob/master/public/js/services/articles.js
https://github.com/jpotts18/mean-stack-relational/blob/master/public/js/controllers/articles.js

**Comment by ammarshadiq** [comment]
Hi Jeff, I tried the implementation above to replace the current export.all function, it works with a little modification on the script,
from 
db.Article.query("select * from articles limit 5")......
to
db.Article.sequelize.query("select * from articles limit 5").....

thanks for the answer and the repo.

**Comment by ammarshadiq** [comment]
Hi Jeff, I got additional question that i couldn't figure out.
I got error in implementing the script to further show it on the front end.
`Error in resource configuration. Expected response to contain an object but got an array`

![Error Page](http://i.imgur.com/4deuEac.png)

Bellow are the detail of my implementation.

I've added the script above by writing on [nodejs controller](https://github.com/jpotts18/mean-stack-relational/blob/master/app/controllers/articles.js)
```javascript
exports.qry = function(req, res) {
    console.log('executing raw query');
    /// Custom query in the node.js backend
    db.Article.sequelize.query("select * from Articles limit 2;").then(function(articles){
        return res.jsonp(articles);
    }).catch(function(err){
        return res.render('error', {
            error: err,
            status: 500
        });
    });
};
```
then I added this to [route] (https://github.com/jpotts18/mean-stack-relational/blob/master/config/routes.js)

```javascript
app.get('/articles/tree',articles.qry);
```

altering [service](https://github.com/jpotts18/mean-stack-relational/blob/master/public/js/services/articles.js)

```javascript
//Articles service used for articles REST endpoint
angular.module('mean.articles').factory("Articles", ['$resource', function($resource) {
    return $resource('articles/:articleId', {
        articleId: '@id'
    }, {
        update: {
            method: 'PUT'
        },
        getData: {
            method: 'GET', url:'/articles/tree'
        }
    });
}]);
```

adding to [controller](https://github.com/jpotts18/mean-stack-relational/blob/master/public/js/controllers/articles.js)

```javascript
 $scope.hier = console.log(Articles.getData());
```

and lastly, accessing it from list [view](https://github.com/jpotts18/mean-stack-relational/blob/master/public/views/articles/list.html)
```javascript
<section data-ng-controller="ArticlesController" data-ng-init="find()">
.....
     {{hier}}
</section>
```

Thank you in advance for your help

**Comment by ammarshadiq** [comment]
ok, slightly editing the [service](https://github.com/jpotts18/mean-stack-relational/blob/master/public/js/services/articles.js) to:

```javascript
//Articles service used for articles REST endpoint
angular.module('mean.articles').factory("Articles", ['$resource', function($resource) {
    return $resource('articles/:articleId', {
        articleId: '@id'
    }, {
        update: {
            method: 'PUT'
        },
        getData: {
           method: 'GET', isArray:true, url:'/categories/tree'
        }
    });
}]);
```
seems to solve my problem.

**Comment by rushingfitness** [comment]
@ammarshadiq can't thank you enough for going through everything you did, even after this was closed. Helped me out immensely!
