### ISSUE TITLE
Google auth does not work

### ISSUE THREAD

**Issue by chaudhryjunaid** [jpotts18/mean-stack-relational#32]
OpenID 2.0 for Google Accounts has gone away
https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by shahidmau** [comment]
I am also getting issue with google login

**Comment by rbonomo** [comment]
Anyone have this worked out?

**Comment by chaudhryjunaid** [comment]
@AhmedHassan07 could you help here too?

**Comment by AhmedHassan07** [comment]
Resolved.
