### ISSUE TITLE
Not usable....

### ISSUE THREAD

**Issue by DaBoogs** [jpotts18/mean-stack-relational#34]
One of the reasons I was looking for a sequalizer generator was to understand, as well as speed up, professional website development. 

Unfortunately, this means we can't use MEANjs or MEANio as they're using mongodb (not useful in MANY applications due to mongo being a dictionary data design making use with relational data impractical).

Fast forward to this git and we run into problems right out of the gate:
-starting out of the box, using "grunt" will wipe the database every, single, time. 
-jade is being used instead of html (html is standard, and most will, or cannot, take the time to learn jade)
-other misc issues

This git would be a LOT more popular had it been constructed properly :(!

Figured you'd like some feedback rather than yet another person avoiding this solution D:

**Comment by chaudhryjunaid** [comment]
Thanks for taking the time Daboogs. To actually avoid db wipe, you need to set sync option in sequelize.js to false after creating the database for the first time. I will add some code soon to make this simpler. Also, implementing a session store is next which would enable a user to remain logged in on grunt or production server restarts. I think I'll get to these items soon.

**Comment by jpotts18** [comment]
@DaBoogs thanks for the feedback!

1. We should remove the automatic database reset. This was used for demonstration purposes, but I can see how it would be frustrating if you don't know how to turn it off. This should probably be moved into a config option pretty easily. 

1. I don't want to substitute Jade for basic HTML. Jade is a templating engine that you can learn in a couple hours which will provide you with a huge increase in productivity.

**Comment by chaudhryjunaid** [comment]
Sync option now included. From now on, the database will only be dropped if invoked with: 

    FORCE_DB_SYNC=true node app

Moreover, a persistent session store has been added so that grunt restarts don't affect development of services that require authorization. Express-Mysql-Session was chosen because available Sequelize based session stores are not well maintained or are buggy.

Reference: Commit 2b0ab2c7993af203ca20b2168edd85923477e1ff

**Comment by jpotts18** [comment]
Nice work Junaid feel free to close this if you think it is resolved!
