### ISSUE TITLE
refactoring to make directory strucuture similar to latest meanjs directory structure

### ISSUE THREAD

**Issue by jayprakash1** [jpotts18/mean-stack-relational#36]
Perhaps it would be good to refactor some codebase so that it is similar to latest meanjs structure. For example: routes, middleware authorization, views, tests etc. 

This would help in reusing some yeoman generators for meanjs.

**Comment by chaudhryjunaid** [comment]
Nice work @jayprakash1! The pull request has been merged. I removed the IIFE syntax from the route files because the node module system (require behavior) makes it redundant.

**Comment by jayprakash1** [comment]
Thanks @jpotts18 and @chaudhryjunaid. This project has been very helpful in re-factoring our MEANJS project to use relational databases. I will be making changes for public files as well and submit pull requests.
