### ISSUE TITLE
mean-stack-relation setup error

### ISSUE THREAD

**Issue by embrasse-moi** [jpotts18/mean-stack-relational#40]
Just setting up mean-stack-relational, It looks as though have a db connection error I can't seem to get figured out, posted below. I have mysql running and I have tested the connection.

Any ideas?

Error: Cannot enqueue Query after fatal error. at Protocol._validateEnqueue (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express-mysql-session/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:193:16) at Protocol._enqueue (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express-mysql-session/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:129:13) at Connection.query (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express-mysql-session/node_modules/mysql-connection-manager/node_modules/mysql/lib/Connection.js:185:25) at SessionStore.get (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express-mysql-session/lib/index.js:151:18) at session (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express-session/index.js:392:11) at Layer.handle [as handle_request] (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/layer.js:82:5) at trim_prefix (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:302:13) at /Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:270:7 at Function.proto.process_params (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:321:12) at next (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:261:10) at methodOverride (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/method-override/index.js:63:14) at Layer.handle [as handle_request] (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/layer.js:82:5) at trim_prefix (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:302:13) at /Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:270:7 at Function.proto.process_params (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:321:12) at next (/Users/embrasse-moi/Documents/CRAIG_CODE/craiglorious/mean-stack-relational/node_modules/express/lib/router/index.js:261:10)

**Comment by jpotts18** [comment]
So my first step would be to check the code that is actually yours. 
`index.js:261:10`

**Comment by embrasse-moi** [comment]
Thanks for the reply! I took a look at router/index.js, That file is unedited from the git clone. So far I have edited development.js, and ran grunt....I guess I was expecting to get a hello world page at this point?

**Comment by chaudhryjunaid** [comment]
@embrasse-moi please check your node version. The node mysql module has an issue with node 4.2.0. Perhaps you are using that. I'll take a look when I can. Meanwhile you can change your node versions or try to update mysql and sequelize dependencies.

**Comment by embrasse-moi** [comment]
I have 4.1.1

**Comment by chaudhryjunaid** [comment]
The project is running perfectly fine. I checked on node 4.1.1 and 4.1.2.
