### ISSUE TITLE
Swap out ngRoute/$routeProvider with ui-router/$urlRouterProvider

### ISSUE THREAD

**Issue by stephenhuh** [jpotts18/mean-stack-relational#42]
ngRoute, though not completely deprecated has been moved into its own Angular module. It'd be beneficial to swap it out for ui-router which allows for [nested-views and more](http://stackoverflow.com/questions/21023763/angularjs-difference-between-angular-route-and-angular-ui-router)!

**Comment by chaudhryjunaid** [comment]
Replaced with ui-router in #52
