### ISSUE TITLE
yoman generator issue

### ISSUE THREAD

**Issue by guohuang** [jpotts18/mean-stack-relational#45]
does anyone having issue with YO generator? i am a mac user, when i run `npm install -g generator-meanjs` i got a lot of errors at the end, is it because the folder structure of meanjs has changed?

here is the error:

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/guo/.nvm/versions/node/v5.1.0/bin/node" "/Users/guo/.nvm/versions/node/v5.1.0/bin/npm" "install" "-g" "generator-meanjs"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.1
npm ERR! path /Users/guo/.nvm/versions/node/v5.1.0/lib/node_modules/generator-meanjs/node_modules/yeoman-generator/node_modules/download/node_modules/caw/node_modules/get-proxy/node_modules/rc/node_modules/deep-extend
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/guo/.nvm/versions/node/v5.1.0/lib/node_modules/generator-meanjs/node_modules/yeoman-generator/node_modules/download/node_modules/caw/node_modules/get-proxy/node_modules/rc/node_modules/deep-extend' -> '/Users/guo/.nvm/versions/node/v5.1.0/lib/node_modules/generator-meanjs/node_modules/deep-extend'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/guo/.nvm/versions/node/v5.1.0/lib/node_modules/generator-meanjs/node_modules/yeoman-generator/node_modules/download/node_modules/caw/node_modules/get-proxy/node_modules/rc/node_modules/deep-extend' -> '/Users/guo/.nvm/versions/node/v5.1.0/lib/node_modules/generator-meanjs/node_modules/deep-extend'

**Comment by chaudhryjunaid** [comment]
Hi @guohuang Please note that mean-stack-relational is a different project than meanjs! We have a yeoman generator on the roadmap but it's not something ready yet. Please post in the meanjs project for your issue!
