### ISSUE TITLE
missing DB create scripts and documentation

### ISSUE THREAD

**Issue by stephen-m-carlson** [jpotts18/mean-stack-relational#47]
I dont see any documentation about how to create the DB.  The DB name is "_mean_relational_", but searching for this string only finds files in /config/env/.  I'm wondering where the SQL dump file is to create the _mean_relational_ db?  When I run the app I get an error `SequelizeConnectionError: ER_BAD_DB_ERROR: Unknown database 'mean_relational'`. Please advise.

**Comment by crdil** [comment]
I believe you need to create the database in MySQL first. "> create database mean_relational;"

**Comment by stephen-m-carlson** [comment]
yes, I figured that out.  Ive got it running now.
The readme should probably be ammended to show that.
//smc

**Comment by stephen-m-carlson** [comment]
it might be good to add that to the readme.md step 5... add instruction to create the blank database and the install scripts will create the needed tables and sample data.
