### ISSUE TITLE
Install docs update

### ISSUE THREAD

**Issue by hairgamiMaster** [jpotts18/mean-stack-relational#48]
Thanks for this project. Just thought I'd let you know the 'bower install' command is missing from the getting started section of the docs. Also, bower install places the components in a 'bower-components' directory under the 'public' directory. The code references them being in 'app/lib/. Not sure if that's something strange about my bower setup, but you need to run bower install, move the 'bower-components' directory inside the public directory and rename it to 'lib'. Otherwise, the app won't run (all kinds of missing files, etc.)

Again, thanks for this contribution. Cheers.

**Comment by hairgamiMaster** [comment]
Guess you need to be running 'grunt' from inside the app directory- that would fix the second part of the problem above. Might want to mention that as well.

**Comment by jpotts18** [comment]
Feel free to send a PR and help other people.

**Comment by chaudhryjunaid** [comment]
hi @hairgamiMaster 
If you look closely at step# 3 in the instructions in README.md, you'll find that doing npm install does three things: 
1. runs npm install
2. runs bower install
3. copies development.json5.sample and production.json5.sample files to development and production.json5
4. runs grunt copy

As for the presence of the lib folder, it could be removed in a future update to use bower components directly. I am looking into it. If you come up with a PR sooner, I'll be only more glad.
