### ISSUE TITLE
Social Login isn't working

### ISSUE THREAD

**Issue by syedfaizan** [jpotts18/mean-stack-relational#55]
I  tried setting up the project and also provided it with fb app id and app secret, but when i click the fb login or signup button , i get CORS error

```
XMLHttpRequest cannot load https://www.facebook.com/dialog/oauth?response_type=code&redirect_uri=http%…facebook%2Fcallback&scope=email%2Cuser_about_me&client_id=xxxx. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

Does anybody know how to resolve this issue?

**Comment by chaudhryjunaid** [comment]
@AhmedHassan07 could you look into this?

**Comment by AhmedHassan07** [comment]
Yes sure. I mention in comments that social login is not working. i will
definitely look into this. This issue is because we have now sign in and
signup pages on angular side so we have to add modules there too. to login
from social network.

**Comment by montera82** [comment]
any update?

**Comment by AhmedHassan07** [comment]
Resolved.

**Comment by AhmedHassan07** [comment]
@chaudhryjunaid  Please close this issue.
