### ISSUE TITLE
using yeoman generator on this stack?

### ISSUE THREAD

**Issue by zenithtekla** [jpotts18/mean-stack-relational#56]
Hi,
Does yeoman auto generator work with your stack?
Or how do I configure (downgrade if required) to get it to work? generating new controllers, models, routes, views, .. automatically by copying user and article patterns.

Thanks

**Comment by chaudhryjunaid** [comment]
Hi @zenithtekla,

Greetings. A yeoman generator is on the roadmap but just not prepared yet. It looks like you'll have to manually base your project on mean-stack-relational.

Thanks
