### ISSUE TITLE
How to make multiple Layouts? 

### ISSUE THREAD

**Issue by sufyan297** [jpotts18/mean-stack-relational#57]
Hello, 
i have used Default layout that points to index.html now i have created login.html that page has different layout i even created **"login_layout.jade"** in Layouts folder and login.jade with index.jade dir

Here is my directory structure...
[http://prntscr.com/c418cn](http://prntscr.com/c418cn)
So my question is how can i point my Angular View (Login Page)  to that Login layout..
please help me 
Thank you..

**Comment by AhmedHassan07** [comment]
You should make your new login view on angular side.and redirect it from angular side.
