### ISSUE TITLE
Error in Windows with the postinstall command

### ISSUE THREAD

**Issue by maticzd** [jpotts18/mean-stack-relational#58]
I get error in Windows because the `cp` command doesn't exist. 
To fix this, I replaced the `postinstall` command with this:

`"postinstall": "bower install && copy config\env\development.json5.sample config\env\development.json5 && copy config\env\production.json5.sample config\env\production.json5 && node node_modules/grunt-cli/bin/grunt copy"`

I hope this will be useful,
Regards.

**Comment by chaudhryjunaid** [comment]
Thanks @maticzd. Your contribution is helpful. You are welcome to maintain a fork of the mean-stack-relational project for windows systems. It should be noted that an Ubuntu environment should have been available in Windows 10 since the anniversary update.
