### ISSUE TITLE
'Session' model table generation fails.

### ISSUE THREAD

**Issue by tyjsoft** [jpotts18/mean-stack-relational#61]
I got this error when attempting to run the app.

SequelizeDatabaseError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes

In the terminal nodemon this was shown by directly after the winston/sequelize "verbose:" logs.  I see the 'Users', and 'Articles' tables being completed, and then showing their indexes, but it seems the error is triggered on the 'Sessions' table creation.  The show index never triggers.  From what I can tell the 'Sessions' model is (kind of) automatically generated from the config/middlewares/seesion.js file.  Is that correct?

I've tried creating the database in various character encodings to no avail.

I'm kind of new at Sequelize, but I wonder if there is some way to address this error as this seems to be a rather frequent occurrence.  There are tons of references to it on SE and other question sites.  Any info you could give, prior to (or in addition to) a fix would be received with great appreciation.  Thanks.

**Comment by chaudhryjunaid** [comment]
@tyjsoft Is it still a concern? I was away from the project for a while and missed all the new issues.
