### ISSUE TITLE
Push rejected, failed to compile Node.js app

### ISSUE THREAD

**Issue by vishesh1king** [jpotts18/mean-stack-relational#62]
I forked your app and deployed in heroku via github as master branch. But the below error occurs. How can i solve this. I want to just see your sample. Do you have any other links ??

bower             ECONFLICT Unable to find suitable version for angular
       
       npm ERR! Linux 3.13.0-105-generic
       npm ERR! argv "/tmp/build_d395c665b5572b1720a72b88ad8f711a/vishesh1king-mean-stack-relational-455ce57/.heroku/node/bin/node" "/tmp/build_d395c665b5572b1720a72b88ad8f711a/vishesh1king-mean-stack-relational-455ce57/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_d395c665b5572b1720a72b88ad8f711a/vishesh1king-mean-stack-relational-455ce57/.npmrc"
       npm ERR! node v4.2.6
       npm ERR! npm  v2.14.22
       npm ERR! code ELIFECYCLE
       npm ERR! mean-stack-relational@0.2.2 postinstall: `bower install && cp config/env/development.json5.sample config/env/development.json5 && cp config/env/production.json5.sample config/env/production.json5 && node node_modules/grunt-cli/bin/grunt copy`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the mean-stack-relational@0.2.2 postinstall script 'bower install && cp config/env/development.json5.sample config/env/development.json5 && cp config/env/production.json5.sample config/env/production.json5 && node node_modules/grunt-cli/bin/grunt copy'.
       npm ERR! This is most likely a problem with the mean-stack-relational package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     bower install && cp config/env/development.json5.sample config/env/development.json5 && cp config/env/production.json5.sample config/env/production.json5 && node node_modules/grunt-cli/bin/grunt copy
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs mean-stack-relational
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!
       npm ERR!     npm owner ls mean-stack-relational
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_d395c665b5572b1720a72b88ad8f711a/vishesh1king-mean-stack-relational-455ce57/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Bower may need a resolution hint for angular
       https://github.com/bower/bower/issues/1746
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by jpbarahona** [comment]
me too! Some fixes?
