### ISSUE TITLE
Routing error?

### ISSUE THREAD

**Issue by angularchobo** [jpotts18/mean-stack-relational#63]
Grunt launches the server, but there is some sort of routing error, so nothing is displayed on the page, other than the title:

Essentially it returns the index everywhere, the '<' is from `<!DOCTYPE html> ... etc`
 
http://i.imgur.com/mB8ImUN.png

**Comment by chaudhryjunaid** [comment]
I'll check it out as soon as I have some time. Perhaps the coming weekend. Thanks for bringing to notice.

**Comment by jpotts18** [comment]
No updates or issue resolutions planned.
